apiVersion: apps/v1
kind: Deployment
metadata:
  name: igwn-peviewer
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: igwn-peviewer
  template:
    metadata:
      labels:
        app: igwn-peviewer
    spec:
      containers:
      - name: igwn-peviewer
        image: ghcr.io/philippeg-ligo/pe-viewer:230126
        ports:
        - name: streamlit
          containerPort: 8501
          protocol: TCP
        resources:
          limit
            cpu: 2000m
            memory: 12G
          requests:
            cpu: 100m
            memory: 4G
